---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure Apache is installed on Debian.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"
